apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: webpvc
    labels:
        name: webpvc
spec:
    accessModes:
        -   ReadWriteOnce
    resources:
        requests:
            storage: 1Gi 
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    env: Production
spec:
  ports:
    - port: 80
  selector:
    env: Production
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
    replicas: 1
    selector: 
        matchLabels:
            env: Production
      
    template:
        metadata: 
            name: web-pod1
            labels:
                env: Production
        spec: 
            containers: 
            -   name: web-con
                image: sunny078/jenkins-kube:v1
                volumeMounts:
                    -   name: website
                        mountPath: /var/www/html
            volumes:
                -   name: website
                    persistentVolumeClaim:
                        claimName: webpvc
               
