apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
   
spec:
  replicas: 3
  selector: 
    matchLabels:
      env: Production
      
  template:
    metadata: 
      name: pod1
      labels:
        env: Production
    spec: 
      containers: 
      - name: pod2-con
        image: sunny078/apache-webserver-php:v1
        
