apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myweb-rs
   
spec:
  replicas: 3
  selector: 
    matchLabels:
      env: Production      
      
  template:
    metadata: 
      name: pod1
      labels:
        env: Production
        
    spec: 
      containers: 
      - name: pod1-con
        image: sunny078/apache-webserver-php:v1
